### ISSUE TITLE
Y-Slide bearing screws don't fit with 8mm rods

### ISSUE THREAD

**Issue by JeffreyRodriguez** [smartfriendz/smartcore#18]
As of the current `master` commit 3e6421612dbdf49b78023343f389bd47144afa30, 8mm Y bearings cannot be properly secured with screws. The screw head and nut are not flush, but blocked by the wall.
# 6mm

![image](https://cloud.githubusercontent.com/assets/505322/8514017/4819f530-2337-11e5-9a2b-c4f6cd17ca20.png)

![image](https://cloud.githubusercontent.com/assets/505322/8514035/f2c8797a-2337-11e5-9397-ef76021225b9.png)
# 8mm

![image](https://cloud.githubusercontent.com/assets/505322/8514022/64607d0e-2337-11e5-90bf-ea96d63a5bd9.png)

![image](https://cloud.githubusercontent.com/assets/505322/8514038/03b26bd8-2338-11e5-8601-03f9ef769a1a.png)

The outer wall is also very thin and prone to breakage.
# Fix

I propose extending the screw plate. There's at least 6mm extra room between the y-slide screw plate and the frame.

**Comment by laxde** [comment]
Also the placement letter (R/L) aren't visible  on version "1.2.4 june 17 2015". I think this is a related problem with the screw plate, i.e. it's the expansion of LM6UU to LM8UU without taking care of the surrounding things.

**Comment by JeffreyRodriguez** [comment]
Fixed in PR #19
