### ISSUE TITLE
Wrong Z slide rendering for 10 and 12 mm rods after latest commits.

### ISSUE THREAD

**Issue by chertykov** [smartfriendz/smartcore#4]
@magillus 
Latest commits remove almost all my changes for 10 and 12 mm rods.

**Comment by smartfriendz** [comment]
Hi magillus,
oops. I didn't check that well. Maybe the last merge removed your changes ? I will check that and update.

**Comment by chertykov** [comment]
Also, 
- code formatting is ugly (wrong indents, tabs mixed with spaces);
- many warnings in openjscad.org code editor;
- too many commented lines like: 

```
            //slideZsupport().translate([40,0,0]),
            //extraSupportBed().translate([0,-50,0])
```

It is necessary to fix ? (Is it desirable to fix or leave it as is ?)
It's not a critics.
It's just a question to you @smartfriendz as a project author.

![2015-03-11 23 24 22](https://cloud.githubusercontent.com/assets/329586/6606063/d496eac4-c845-11e4-8918-e3277227762f.png)
